import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'

const About = () =>{

    return(
        <>
            <Head>
                <title>About | Sea Food A Hotal and Restaurants</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <Footer />
        </>
    )
}
export default About