import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function Home() {
  return (
      <>
      <Head>
        <title>Sea Food A Hotal and Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="banner">
      <Header />
      <div className="logo">
        <a href="/"><img src="images/logo.png" alt="" /></a>
      </div>
      <div className="slider">
        <section className="slider">
          <div className="flexslider">
            <ul className="slides">
              <li>
                <p>
                  Hen an unknown printer took a galley of type and scrambled it
                  to make a type specimen<br />
                  book. It has survived not only five centuries, but also the
                  leap into electronic
                </p>
              </li>
              <li>
                <p>
                  In a free hour, when our power of choice is untrammelled and
                  when nothing prevents our being<br />
                  able to do what we like best, every pleasure is to be welcomed
                  and every pain avoided.
                </p>
              </li>
              <li>
                <p>
                  Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut
                  odit aut fugit, sed quia consequuntur<br />
                  magni dolores eos qui ratione voluptatem sequi nesciunt.
                </p>
              </li>
            </ul>
          </div>
        </section>
      </div>
      </div>
      <div className="seegrid">
      <div className="container">
        <div className="seegrid-main">
          <div className="col-md-6 seegrid-left">
            <span className="flyfish"> </span>
            <h3>MANY DESKTOP PUBLISHING PACKAGES AND WEB PAG</h3>
            <p>
              the first true generator on the Internet. It uses adictionary of
              over 200 Latin words, combined witha handful of model sentence
              structures, togenerate Lorem Ipsum which looks reasonable. The
              generated Lorem
            </p>
            <p>
              the first true generator on the Internet. It uses adictionary of
              over 200 Latin words, combined witha handful of model sentence
              structures, togenerate Lorem Ipsum which looks reasonable. The
              generated Lorem
            </p>
          </div>
          <div className="col-md-6 seegrid-right">
            <img src="images/gr.jpg" alt="" />
          </div>
          <div className="clearfix"></div>
        </div>
      </div>
    </div>
    <div className="gallery-inf">
      <div className="container">
        <div className="gallery-main">
          <div className="work-bottom">
            <ul id="filters" className="clearfix">
              <li>
                <span className="filter cr" data-filter="app card icon logo web">
                </span>
              </li>
              <li><span className="filter fi" data-filter="app"> </span></li>
              <li><span className="filter san" data-filter="card"> </span></li>
              <li><span className="filter octo" data-filter="icon"> </span></li>
            </ul>
            <div id="portfoliolist">
              <div
                className="portfolio app mix_all"
                data-cat="app"
                style={{display:"inline-block", opacity:1}}>
                <div className="portfolio-wrapper">
                  <a
                    href="single.html"
                    className="b-link-stripe b-animate-go thickbox"
                  >
                    <img src="images/gr1.jpg" />
                    <div className="b-wrapper">
                      <h2 className="b-animate b-from-left b-delay03"></h2></div
                  ></a>
                </div>
              </div>
              <div
                className="portfolio icon mix_all"
                data-cat="icon"
                style={{display: "inline-block", opacity: 1 }}
              >
                <div className="portfolio-wrapper">
                  <a
                    href="single.html"
                    className="b-link-stripe b-animate-go thickbox"
                  >
                    <img src="images/gr2.jpg" />
                    <div className="b-wrapper">
                      <h2 className="b-animate b-from-left b-delay03"></h2></div
                  ></a>
                </div>
              </div>
              <div
                className="portfolio card mix_all"
                data-cat="card"
                style={{display: "inline-block", opacity: 1 }}
              >
                <div className="portfolio-wrapper">
                  <a
                    href="single.html"
                    className="b-link-stripe b-animate-go thickbox"
                  >
                    <img src="images/gr3.jpg" />
                    <div className="b-wrapper">
                      <h2 className="b-animate b-from-left b-delay03"></h2></div
                  ></a>
                </div>
              </div>
              <div
                className="portfolio logos mix_all"
                data-cat="logo"
                style={{display: "inline-block", opacity: 1 }}
              >
                <div className="portfolio-wrapper">
                  <a
                    href="single.html"
                    className="b-link-stripe b-animate-go thickbox"
                  >
                    <img src="images/gr4.jpg" />
                    <div className="b-wrapper">
                      <h2 className="b-animate b-from-left b-delay03"></h2></div
                  ></a>
                </div>
              </div>
              <div
                className="portfolio card mix_all"
                data-cat="card"
                style={{display: "inline-block", opacity: 1 }}
              >
                <div className="portfolio-wrapper">
                  <a
                    href="single.html"
                    className="b-link-stripe b-animate-go thickbox"
                  >
                    <img src="images/gr5.jpg" />
                    <div className="b-wrapper">
                      <h2 className="b-animate b-from-left b-delay03"></h2></div
                  ></a>
                </div>
              </div>
              <div
                className="portfolio app mix_all"
                data-cat="app"
                style={{display: "inline-block", opacity: 1 }}
              >
                <div className="portfolio-wrapper">
                  <a
                    href="single.html"
                    className="b-link-stripe b-animate-go thickbox"
                  >
                    <img src="images/gr6.jpg" />
                    <div className="b-wrapper">
                      <h2 className="b-animate b-from-left b-delay03"></h2></div
                  ></a>
                </div>
              </div>
            </div>
            <div className="clearfix"></div>
          </div>
          <div className="clearfix"></div>
        </div>
      </div>
    </div>
    <div className="see-info">
      <div className="container">
        <div className="see-info-main">
          <div className="see-info-top">
            <span className="mess"> </span>
            <h3>RECENT NEWS</h3>
            <span className="long-line"> </span>
            <p>
              content here', making it look like readable English. Many desktop
              publishing packages and web page editors now use Lorem Ipsum as
              their default model text,
            </p>
          </div>
          <div className="see-info-bottom">
            <div className="see-info-grid">
              <img src="images/bis.jpg" alt="" />
              <h3>YOU NEED TO BE SURE THERE</h3>
              <span className="line"> </span>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content
              </p>
              <div className="see-info-bwn">
                <a href="#">LEARN MORE</a>
              </div>
            </div>
            <div className="see-info-grid">
              <img src="images/stra.jpg" alt="" />
              <h3>YOU NEED TO BE SURE THERE</h3>
              <span className="line"> </span>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content
              </p>
              <div className="see-info-bwn">
                <a href="#">LEARN MORE</a>
              </div>
            </div>
            <div className="see-info-grid inf">
              <img src="images/sup.jpg" alt="" />
              <h3>YOU NEED TO BE SURE THERE</h3>
              <span className="line"> </span>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content
              </p>
              <div className="see-info-bwn">
                <a href="#">LEARN MORE</a>
              </div>
            </div>
            <div className="clearfix"></div>
          </div>
          <div className="clearfix"></div>
        </div>
      </div>
    </div>
      <Footer />
      </>

  )
}
